[versions]
slf4j = "2.0.17"
logback = "1.5.21"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
logging = ["slf4j-api", "logback-classic"]
